image:
  file: .gitpod.dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 5037
    onOpen: ignore
vscode:
  extensions:
    - Dart-Code.flutter@3.7.1:gujVOCgsbgoN2/po8X1tfA==
    - Dart-Code.dart-code@3.7.1:3XT4xvtPoRdNasA5smNMiA==
